# Generated by Django 4.2.5 on 2023-11-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_productdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDb',
            new_name='VehicleDb',
        ),
    ]
