# Generated by Django 4.2.5 on 2023-11-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_rename_productdb_vehicledb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledb',
            name='VehiclePrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
