# Generated by Django 4.2.5 on 2023-11-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_vehicledb_vehicleprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledb',
            name='BrandName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
