# Generated by Django 4.2.5 on 2023-11-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_vehicledb_brandname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bikedetailsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EngineCapacity', models.CharField(blank=True, max_length=100, null=True)),
                ('Mileage', models.IntegerField(blank=True, null=True)),
                ('Fueltankcapacity', models.IntegerField(blank=True, null=True)),
                ('Maxpower', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
