# Generated by Django 4.2.5 on 2023-11-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_bikedetailsdb_vehiclename_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bikedetailsdb',
        ),
        migrations.AddField(
            model_name='vehicledb',
            name='Enginecapacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicledb',
            name='Fuelcapacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicledb',
            name='Maxpower',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicledb',
            name='Mileage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
