# Generated by Django 4.2.5 on 2023-11-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makeatripdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(blank=True, max_length=100, null=True)),
                ('dropoff_location', models.CharField(blank=True, max_length=100, null=True)),
                ('picup_date', models.IntegerField(blank=True, null=True)),
                ('dropoff_date', models.IntegerField(blank=True, null=True)),
                ('pickup_time', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
