# Generated by Django 4.2.5 on 2023-11-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeatripdb',
            name='dropoff_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makeatripdb',
            name='picup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
